import { useState } from 'react';
import type { AppProps } from 'next/app'
import { Slider, MenuItem, Select, Checkbox, Button } from '@mui/material'
import MapChart from "./../Components/Mapa/App";
import '../styles/globals.css';
import './../styles/FilterSite.scss';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee, faPlane, faBus } from '@fortawesome/free-solid-svg-icons'
import CountrySelect from '../Components/Mapa/CountrySelect';
import NavBar from '../Components/NavBar';
import Carousel from '../Components/SharedComponents/Swiper';
import GeneralInfo from '../Components/LandingPage/GeneralInfo';
import FeaturedTures from '../Components/LandingPage/FeaturedTures';
import Head from 'next/head'


function MyApp({ Component, pageProps }: AppProps) {
    const [content, setContent] = useState("");
    const [price, setPrice] = useState<any>(5000)
    const [transport, setTransport] = useState("any")
    const [country, setCountry] = useState<null | string>(null)
    return (
        <div style={{  }} className="">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
           
                <NavBar />

            <section style={{ maxHeight: "95vh" }}> 
            <Carousel />
            </section>
            <section>
            <GeneralInfo />
            </section>
            <section>
                <FeaturedTures/>
            </section>
            <div className="FilterMain">

                <section className="FilterTitle"><h1>Explore the world with compass</h1></section>

                <section className="FilterMainSectionOne" style={{ backgroundColor: "white" }}>

                <MapChart Transport={transport} Price={price} Country={country} setTooltipContent={setContent} />
              
                </section>


            <section className="FilterMainSectionTwo">
                    <article className="FilterMainArticle">
                        <div >
                    <p>Price</p>
                <Slider defaultValue={5000} onChange={(event, val) => {
                    setPrice(val)
                    }} aria-label="Default" valueLabelDisplay="auto" max={5000} />
                    <p style={{textAlign:"center"}}>0 EUR-{price} EUR</p>
                    <p>Transportation</p>
                    <section>
                        <Checkbox checked={transport === "any"} onChange={(e) => { if (e.target.checked) setTransport("any") }} color="secondary" />
                        <span>any</span>
                    </section>
                    <section style={{ color: "orange", fontWeight: 600, fontFamily: "sans-serif" }}>
                        <Checkbox checked={transport === "bus"} onChange={(e) => { if (e.target.checked) setTransport("bus") }} color="secondary" />
                        <span style={{ marginRight: "1rem" }}>bus</span>

                        <span style={{ width: "1rem" }}>
                            <FontAwesomeIcon size="xs" icon={faBus} />
                        </span>
                    </section>
                    <section style={{ color: "green", fontWeight: 600, fontFamily: "sans-serif" }}>
                        <Checkbox checked={transport === "plane"} onChange={(e) => { if (e.target.checked) setTransport("plane") }} color="secondary" />
                        <span style={{ marginRight: "1rem" }}>airplane</span>
                        <span style={{ width: "1rem" }}>
                            <FontAwesomeIcon size="xs" icon={ faPlane}/>
                        </span>
                        </section>

                    <p>Country</p>
                    <CountrySelect setCountry={(val: null | string) => setCountry(val)} />
                    <section style={{ display: "flex", justifyContent: "center", alignItems: "center", marginTop:"1rem" }}>
                    <Button  variant="contained">Apply</Button>
                        </section>
                 </div>
                    </article>
           </section>
                </div>
                </div>
      
    );
}
export default MyApp
